name: cron
on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  deploy:
    name: Deploy to Servers
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SSH_IP }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          connect_timeout: 10s
          script: |
            cd /home/apicon/service/chunzhen/qqwry

            rm -rfv temp
            mkdir temp
            cd temp

            wget https://github.com/out0fmemory/qqwry.dat/raw/master/qqwry_lastest.dat
            rm ../qqwry.dat
            cp qqwry_lastest.dat ../qqwry.dat

            docker restart Service_Chunzhen
